# Generated by Django 5.0.6 on 2024-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254, verbose_name='E-mail автора')),
                ('author_full_name', models.CharField(max_length=255, verbose_name='ФИО автора')),
                ('topic', models.TextField(verbose_name='Название статьи')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
