# Generated by Django 5.0.6 on 2024-09-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at'], 'verbose_name': 'публикация', 'verbose_name_plural': 'публикации'},
        ),
    ]
