# Generated by Django 5.0.6 on 2024-08-06 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.FileField(blank=True, null=True, upload_to='news', verbose_name='Изображение')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('reading_time', models.IntegerField(verbose_name='Время чтения в минутах')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-date_created'],
            },
        ),
    ]
