# Generated by Django 5.0.6 on 2024-08-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailrecipient',
            options={'verbose_name': 'получатель почты', 'verbose_name_plural': 'получатели почты (коллективные заявки, обращения)'},
        ),
    ]
