# Generated by Django 5.0.6 on 2024-08-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('for_whom', models.CharField(blank=True, choices=[('PRESCHOOLERS', 'Дошкольники'), ('TEACHERS', 'Учителя'), ('KINDERGARTENER', 'Воспитатели'), ('STUDENTS', 'Студенты')], max_length=15, null=True, verbose_name='Для кого')),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс'), (12, 'Вузовские олимпиады')], null=True, verbose_name='Класс')),
                ('subject', models.CharField(blank=True, choices=[('ENGLISH_LANGUAGE', 'Английский язык'), ('LIBRARY', 'Библиотечное дело'), ('BIOLOGY', 'Биология'), ('EDUCATIONAL_WORK', 'Воспитательная работа'), ('GEOGRAPHY', 'География'), ('ADDITIONAL_EDUCATION', 'Доп. образование'), ('PRESCHOOL_EDUCATION', 'Дошкольное образование'), ('ART', 'ИЗО'), ('FOREIGN_LANGUAGES', 'Иностранные языки'), ('COMPUTER_SCIENCE', 'Информатика'), ('HISTORY', 'История'), ('CLASS_MANAGEMENT', 'Классное руководство'), ('MATHS', 'Математика'), ('MUSIC', 'Музыка'), ('PRIMARY_CLASSES', 'Начальные классы'), ('LIFE_SAFETY', 'ОБЖ'), ('SPECIAL_EDUCATION', 'Обучение детей с ОВЗ'), ('SOCIAL_SCIENCE', 'Обществознание'), ('ENVIRONMENTAL_STUDIES', 'Окружающий мир'), ('RELIGIOUS_CULTURES', 'Основы религиозных культур'), ('LABOR_SAFETY', 'Охрана труда'), ('LAW', 'Право'), ('RUSSIAN_LITERATURE', 'Русская литература'), ('RUSSIAN_LANGUAGE', 'Русский язык'), ('SOCIAL_PEDAGOGY', 'Социальному педагогу'), ('TECHNOLOGY', 'Технология'), ('PHYSICS', 'Физика'), ('PHYSICAL_CULTURE', 'Физкультура'), ('CHEMISTRY', 'Химия'), ('SCHOOL_PSYCHOLOGIST', 'Школьному психологу'), ('ECONOMICS', 'Экономика')], max_length=50, null=True, verbose_name='Предмет')),
                ('is_show', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Показывается')),
            ],
            options={
                'verbose_name': 'олимпиада',
                'verbose_name_plural': 'олимпиады',
                'db_table': 'olympiad',
            },
        ),
        migrations.CreateModel(
            name='OlympiadQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255, verbose_name='Вопрос')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='olympiads.olympiad', verbose_name='Олимпиада')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'db_table': 'olympiad_questions',
            },
        ),
        migrations.CreateModel(
            name='OlympiadAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Название')),
                ('is_correct', models.BooleanField(choices=[(True, 'Правильный'), (False, 'Неправильный')], verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='olympiads.olympiadquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответа',
                'db_table': 'olympiad_answer_options',
            },
        ),
    ]
