# Generated by Django 5.0.6 on 2024-08-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Для кого',
                'verbose_name_plural': 'Для кого',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='for_whom',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='subject',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='for_whom',
            field=models.ManyToManyField(to='olympiads.forwhom', verbose_name='Для кого'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='subject',
            field=models.ManyToManyField(to='olympiads.subject', verbose_name='Предмет'),
        ),
    ]
