# Generated by Django 5.0.6 on 2024-08-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_forwhom_subject_remove_olympiad_for_whom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olympiad',
            old_name='subject',
            new_name='subjects',
        ),
    ]
