# Generated by Django 5.0.6 on 2024-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0003_rename_subject_olympiad_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='subjects',
            field=models.ManyToManyField(to='olympiads.subject', verbose_name='Предметы'),
        ),
    ]
