# Generated by Django 5.0.6 on 2024-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0004_alter_olympiad_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadansweroption',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='olympiadquestion',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
