# Generated by Django 5.0.6 on 2024-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageFAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OLYMPIADS', 'Олимпиады'), ('COURSES', 'Курсы'), ('PUBLICATIONS', 'Публикации'), ('ARTICLES_PUBLICATION', 'Публикация статей'), ('FAQ_OLYMPIADS_AND_COMPETITIONS', 'Олимпиады и конкурсы (FAQ)'), ('FAQ_COURSES', 'Курсы (FAQ)'), ('PAYMENT_AND_DELIVERY', 'Оплата и доставка'), ('CREATIVE_COMPETITION', 'Творческий конкурс'), ('INTERNATIONAL_COMPETITION_REGULATIONS', 'Положение о Международном конкурсе')], max_length=255, verbose_name='Страница')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('image', models.FileField(blank=True, null=True, upload_to='faq_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
