# Generated by Django 5.0.6 on 2024-08-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('olympiads', '0002_forwhom_subject_remove_olympiad_for_whom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='education_degree',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='education_degree',
            field=models.ManyToManyField(to='courses.educationdegree', verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(to='olympiads.subject', verbose_name='Предмет'),
        ),
    ]
