# Generated by Django 5.0.6 on 2024-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_educationdegree_remove_course_education_degree_and_more'),
        ('olympiads', '0003_rename_subject_olympiad_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='olympiads.subject', verbose_name='Предметы'),
        ),
    ]
