# Generated by Django 5.0.6 on 2024-08-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_subject_course_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
