# Generated by Django 5.0.6 on 2024-08-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_usercourse_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabusmodule',
            name='number_of_control_hours',
            field=models.IntegerField(default=2, verbose_name='Кол-во часов контроля'),
        ),
    ]
