# Generated by Django 5.0.6 on 2024-09-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursesyllabusmodule_number_of_control_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
