# Generated by Django 5.0.6 on 2024-10-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teaching_materials',
            field=models.FileField(blank=True, null=True, upload_to='courses/materials', verbose_name='Методические материалы'),
        ),
    ]
