# Generated by Django 5.0.6 on 2024-11-18 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_usercourse_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлен'),
        ),
    ]
