# Generated by Django 5.0.6 on 2024-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('ACCEPTED', 'В обработке'), ('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка')], default='ACCEPTED', max_length=8, verbose_name='Статус')),
                ('reason', models.CharField(choices=[('REPLENISHMENT', 'Пополнение'), ('PAYMENT', 'Покупка')], max_length=15, verbose_name='Причина')),
                ('balance', models.CharField(choices=[('MAIN', 'Основной'), ('BONUS', 'Бонусный')], max_length=5, verbose_name='Баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
    ]
