# Generated by Django 5.0.6 on 2024-08-06 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Цена')),
                ('tag', models.CharField(max_length=3, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО участника')),
                ('institution_name', models.CharField(max_length=255, verbose_name='Название учреждения')),
                ('locality', models.CharField(max_length=255, verbose_name='Населённый пункт')),
                ('is_paid', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Оплачен')),
                ('participation_date', models.DateField(blank=True, null=True, verbose_name='Дата участия')),
                ('for_whom', models.CharField(blank=True, choices=[('PARTICIPANT', 'Участник'), ('LEADER', 'Руководитель')], max_length=11, null=True, verbose_name='Для кого')),
                ('nomination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номинация')),
                ('place', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 место'), (2, '2 место'), (3, '3 место'), (4, 'Участник')], null=True, verbose_name='Место')),
                ('level', models.CharField(blank=True, choices=[('INTNAT', 'Международный'), ('ALRUSS', 'Всероссийский'), ('INTREG', 'Межрегиональный')], max_length=6, null=True, verbose_name='Тип конкурса')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название работы')),
                ('additional_nomination', models.IntegerField(blank=True, choices=[(1, 'за активное участие в интернет-олимпиадах на портале “Росмедаль” и достижения в профессиональном мастерстве'), (2, 'за высокий уровень подготовки участников Международного творческого конкурса, проводимого на портале “Росмедаль”'), (3, 'за активную публикацию статей и методических материалов на портале “Росмедаль”'), (4, 'за активную помощь в наполнении Международного образовательного портала “Росмедаль”'), (5, 'за активное участие в творческих конкурсах, конкурсах профессионального мастерства и подготовку участников-лауреатов олимпиад на портале “Росмедаль”'), (6, 'за плодотворное сотрудничество и подготовку участников олимпиад и конференций на портале “Росмедаль”'), (7, 'за особые достижения в профессиональной деятельности'), (8, 'за успешное внедрение современных технологий'), (9, 'за личный вклад во внедрение новых методик обучения'), (10, 'за постоянное повышение профессиональной компетентности и ответственности с пожеланием успехов в ответственной работе, новых творческих идей и замыслов, осуществления запланированных дел'), (11, 'за выдающиеся профессиональные качества'), (12, 'за высокий профессионализм, творческий поиск и упорный труд'), (13, 'за активное участие и подготовку участников-лауреатов олимпиад на портале “Росмедаль”')], null=True, verbose_name='Номинация в благодарственном письме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='courses.usercourse', verbose_name='Курс')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.documentvariation', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
    ]
