# Generated by Django 5.0.6 on 2024-10-01 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='docs.document', verbose_name='Приложение'),
        ),
        migrations.CreateModel(
            name='DocumentVariationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(verbose_name='HTML-Шаблон')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='docs.documentvariation')),
            ],
            options={
                'verbose_name': 'шаблон документа',
                'verbose_name_plural': 'шаблоны документов',
            },
        ),
    ]
