# Generated by Django 5.0.6 on 2024-10-02 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_attachment_documentvariationtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='attachment',
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.documentvariationtemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='documentvariation',
            name='tag',
            field=models.CharField(max_length=4, verbose_name='Тэг'),
        ),
    ]
