# Generated by Django 5.0.6 on 2024-10-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_document_attachment_document_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvariationtemplate',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='documents/tempates/previews', verbose_name='Превью'),
        ),
    ]
