# Generated by Django 5.0.6 on 2024-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_documentvariationtemplate_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='leader',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='documentvariationtemplate',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='documents/templates/previews', verbose_name='Превью'),
        ),
    ]
