# Generated by Django 5.0.6 on 2024-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_document_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кто опубликовал'),
        ),
        migrations.AddField(
            model_name='document',
            name='qr_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для QR-кода'),
        ),
    ]
