# Generated by Django 5.0.6 on 2024-11-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_document_published_by_document_qr_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentvariationtemplate',
            name='template',
        ),
    ]
