# Generated by Django 5.0.6 on 2024-11-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_remove_documentvariationtemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvariationtemplate',
            name='additional_preview',
            field=models.FileField(blank=True, null=True, upload_to='documents/templates/previews', verbose_name='Доп. превью'),
        ),
    ]
