# Generated by Django 5.0.6 on 2024-11-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_documentvariationtemplate_additional_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='qr_link',
        ),
    ]
