# Generated by Django 5.0.6 on 2024-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дом доставки'),
        ),
    ]
