# Generated by Django 5.0.6 on 2024-11-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_delivery_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Квалификация в соответствии с документом об образовании'),
        ),
    ]
