# Generated by Django 5.0.6 on 2024-08-06 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('nomination', models.CharField(max_length=255, verbose_name='Номинация')),
                ('author_full_name', models.TextField(verbose_name='ФИО автора')),
                ('author_email', models.EmailField(max_length=254, verbose_name='E-mail автора')),
                ('place', models.IntegerField(verbose_name='Занятое место')),
                ('level', models.CharField(choices=[('INTNAT', 'Международный'), ('ALRUSS', 'Всероссийский'), ('INTREG', 'Межрегиональный')], max_length=255, verbose_name='Уровень конкурса')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'конкурсная работа',
                'verbose_name_plural': 'конкурсные работы',
            },
        ),
    ]
