# Generated by Django 5.0.6 on 2024-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestWorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(verbose_name='Место')),
            ],
            options={
                'verbose_name': 'выпадающее место',
                'verbose_name_plural': 'выпадающие места',
            },
        ),
    ]
